apiVersion: v1
kind: Service
metadata:
  name: owui
  namespace: owui
  labels:
    app: owui
spec:
  selector:
    app: owui
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 8080 
      targetPort: 8080 
      name: http
